name: Linux
on: [push, pull_request]
jobs:
  linux:
    name: "Build and test on Linux"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          set -eux
          sudo apt install -y libedit-dev
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Compile the project
        run: make
      - name: Runt tests
        run: make test
